import type { BiomeDefinition, BiomeId, BiomePropEntry } from './types';

const plainsProps: BiomePropEntry[] = [
  { kind: 'dirt-01', weight: 12 },
  { kind: 'dirt-02', weight: 12 },
  { kind: 'dirt-03', weight: 10 },
  { kind: 'dirt-04', weight: 5 },
  { kind: 'dirt-05', weight: 2 },
  { kind: 'dirt-06', weight: 2 },
  { kind: 'dirt-07', weight: 2 },
  { kind: 'dirt-08', weight: 2 },
  { kind: 'tree-01', weight: 12 },
  { kind: 'tree-02', weight: 7 },
  { kind: 'tree-03', weight: 7 },
  { kind: 'tree-05', weight: 5 },
  { kind: 'tree-06', weight: 1 },  
  { kind: 'tree-10', weight: 2 },
  { kind: 'tree-12', weight: 1 },
  { kind: 'tree-13', weight: 1 },
  { kind: 'bush-01', weight: 8 },
  { kind: 'bush-02', weight: 7 },
  { kind: 'bush-03', weight: 7 },
  { kind: 'bush-04', weight: 7 },
  { kind: 'bush-05', weight: 6 },
  { kind: 'bush-06', weight: 4 },
  { kind: 'bush-07', weight: 4 },

  { kind: 'rock-03', weight: 3 },
  { kind: 'rock-04', weight: 2 },
  { kind: 'rock-05', weight: 2 },
  { kind: 'rock-06', weight: 2 },

  { kind: 'flower-01', weight: 4 },
  { kind: 'flower-02', weight: 4 },
  { kind: 'flower-03', weight: 4 },
  { kind: 'flower-04', weight: 4 },
  { kind: 'flower-05', weight: 4 },
  { kind: 'flower-06', weight: 3 },
  { kind: 'flower-07', weight: 3 },
  { kind: 'flowerbed-01', weight: 5 },
  { kind: 'flowerbed-02', weight: 3 },
  { kind: 'mushroom-01', weight: 5 },
  { kind: 'mushroom-02', weight: 4 },
  { kind: 'stump-01', weight: 3 },
  { kind: 'stump-02', weight: 3 },
  { kind: 'dead-tree-01', weight: 1 },
  { kind: 'dead-tree-02', weight: 1 },
  { kind: 'dead-tree-03', weight: 1 },
  { kind: 'rubble-01', weight: 1 },
  { kind: 'rubble-02', weight: 1 },
  { kind: 'rubble-03', weight: 1 },
];

export const biomeDefinitions: Record<BiomeId, BiomeDefinition> = {
  'biome-01': {
    id: 'biome-01',
    name: 'Green Plains',
    ground: {
      base: '#acd27d',
      light: '#b9db8b',
      dark: '#9bc76f',
      detail: ['#e8d668', '#e9dce0', '#709b45'],
    },
    ambient: 'leaves',
    propDensity: 1,
    props: plainsProps,
    enemies: [
      { id: 'minion-01', weight: 30 },
      { id: 'minion-04', weight: 24 },
      { id: 'minion-02', weight: 24 },
      { id: 'minion-03', weight: 16 },
      { id: 'minion-09', weight: 6 },
    ],
  },
  'biome-02': {
    id: 'biome-02',
    name: 'Soil Badlands',
    ground: {
      base: '#b8804d',
      light: '#c99057',
      dark: '#98683f',
      detail: ['#d2a06a', '#7b5638', '#c7a36b'],
    },
    ambient: 'dust',
    propDensity: 0.8,
    props: [
      { kind: 'prop-064', weight: 5 },
      { kind: 'prop-065', weight: 5 },
      { kind: 'prop-066', weight: 8 },
      { kind: 'prop-067', weight: 8 },
      { kind: 'prop-068', weight: 9 },
      { kind: 'prop-069', weight: 8 },
      { kind: 'prop-070', weight: 4 },
      { kind: 'prop-071', weight: 3 },
      { kind: 'prop-072', weight: 2 },
      { kind: 'prop-073', weight: 2 },
      { kind: 'prop-074', weight: 2 },
      { kind: 'prop-075', weight: 2 },
    ],
    enemies: [
      { id: 'minion-04', weight: 28 },
      { id: 'minion-03', weight: 24 },
      { id: 'minion-09', weight: 20 },
      { id: 'minion-05', weight: 18 },
      { id: 'minion-06', weight: 10 },
    ],
  },
  'biome-03': {
    id: 'biome-03',
    name: 'Golden Desert',
    ground: {
      base: '#dfbc62',
      light: '#edcc77',
      dark: '#c79b48',
      detail: ['#f1d890', '#a97832', '#78a36f'],
    },
    ambient: 'dust',
    propDensity: 0.66,
    props: [
      { kind: 'prop-076', weight: 4 },
      { kind: 'prop-077', weight: 4 },
      { kind: 'prop-078', weight: 12 },
      { kind: 'prop-079', weight: 10 },
      { kind: 'prop-080', weight: 5 },
      { kind: 'prop-081', weight: 7 },
      { kind: 'prop-082', weight: 5 },
      { kind: 'prop-083', weight: 2 },
      { kind: 'prop-084', weight: 2 },
      { kind: 'prop-085', weight: 2 },
      { kind: 'prop-086', weight: 2 },
      { kind: 'prop-087', weight: 5 },
    ],
    enemies: [
      { id: 'minion-03', weight: 24 },
      { id: 'minion-05', weight: 26 },
      { id: 'minion-06', weight: 18 },
      { id: 'minion-07', weight: 16 },
      { id: 'minion-09', weight: 16 },
    ],
  },
  'biome-04': {
    id: 'biome-04',
    name: 'Murkfen Swamp',
    ground: {
      base: '#5f7540',
      light: '#748b4d',
      dark: '#3d5433',
      detail: ['#94a96b', '#344c36', '#5d7f76'],
    },
    ambient: 'none',
    propDensity: 0.9,
    props: [
      { kind: 'prop-088', weight: 7 },
      { kind: 'prop-089', weight: 8 },
      { kind: 'prop-090', weight: 10 },
      { kind: 'prop-091', weight: 5 },
      { kind: 'prop-092', weight: 8 },
      { kind: 'prop-093', weight: 7 },
      { kind: 'prop-094', weight: 5 },
      { kind: 'prop-095', weight: 4 },
      { kind: 'prop-096', weight: 2 },
      { kind: 'prop-097', weight: 2 },
      { kind: 'prop-098', weight: 2 },
      { kind: 'prop-099', weight: 2 },
    ],
    enemies: [
      { id: 'minion-02', weight: 26 },
      { id: 'minion-04', weight: 20 },
      { id: 'minion-06', weight: 18 },
      { id: 'minion-08', weight: 20 },
      { id: 'minion-09', weight: 16 },
    ],
  },
  'biome-05': {
    id: 'biome-05',
    name: 'Deep Forest',
    ground: {
      base: '#6da85a',
      light: '#82bd6b',
      dark: '#47793f',
      detail: ['#b8d36a', '#5d8d3e', '#d9b24c'],
    },
    ambient: 'leaves',
    propDensity: 1.08,
    props: [
      { kind: 'prop-100', weight: 6 },
      { kind: 'prop-101', weight: 8 },
      { kind: 'prop-102', weight: 10 },
      { kind: 'prop-103', weight: 10 },
      { kind: 'prop-104', weight: 12 },
      { kind: 'prop-105', weight: 12 },
      { kind: 'prop-106', weight: 5 },
      { kind: 'prop-107', weight: 4 },
      { kind: 'prop-108', weight: 2 },
      { kind: 'prop-109', weight: 2 },
      { kind: 'prop-110', weight: 2 },
      { kind: 'prop-111', weight: 2 },
    ],
    enemies: [
      { id: 'minion-01', weight: 22 },
      { id: 'minion-02', weight: 28 },
      { id: 'minion-04', weight: 24 },
      { id: 'minion-08', weight: 14 },
      { id: 'minion-09', weight: 12 },
    ],
  },
  'biome-06': {
    id: 'biome-06',
    name: 'Cinder Volcano',
    ground: {
      base: '#383636',
      light: '#4b4947',
      dark: '#252525',
      detail: ['#e26c26', '#8f2e1f', '#d2b24c'],
    },
    ambient: 'dust',
    propDensity: 0.72,
    props: [
      { kind: 'prop-112', weight: 5 },
      { kind: 'prop-113', weight: 4 },
      { kind: 'prop-114', weight: 9 },
      { kind: 'prop-115', weight: 6 },
      { kind: 'prop-116', weight: 5 },
      { kind: 'prop-117', weight: 7 },
      { kind: 'prop-118', weight: 4 },
      { kind: 'prop-119', weight: 2 },
      { kind: 'prop-120', weight: 2 },
      { kind: 'prop-121', weight: 2 },
      { kind: 'prop-122', weight: 2 },
      { kind: 'prop-123', weight: 2 },
    ],
    enemies: [
      { id: 'minion-05', weight: 22 },
      { id: 'minion-06', weight: 22 },
      { id: 'minion-07', weight: 24 },
      { id: 'minion-08', weight: 18 },
      { id: 'minion-09', weight: 14 },
    ],
  },
  'biome-07': {
    id: 'biome-07',
    name: 'Snowland',
    ground: {
      base: '#d8e9ef',
      light: '#edf7f9',
      dark: '#a8c3d0',
      detail: ['#f8ffff', '#7fa8c5', '#4c8fb8'],
    },
    ambient: 'none',
    propDensity: 0.82,
    props: [
      { kind: 'prop-124', weight: 6 },
      { kind: 'prop-125', weight: 5 },
      { kind: 'prop-126', weight: 8 },
      { kind: 'prop-127', weight: 6 },
      { kind: 'prop-128', weight: 13 },
      { kind: 'prop-129', weight: 6 },
      { kind: 'prop-130', weight: 4 },
      { kind: 'prop-131', weight: 4 },
      { kind: 'prop-132', weight: 2 },
      { kind: 'prop-133', weight: 2 },
      { kind: 'prop-134', weight: 2 },
      { kind: 'prop-135', weight: 2 },
    ],
    enemies: [
      { id: 'minion-01', weight: 20 },
      { id: 'minion-03', weight: 18 },
      { id: 'minion-06', weight: 24 },
      { id: 'minion-07', weight: 20 },
      { id: 'minion-08', weight: 18 },
    ],
  },
};

export function getBiome(id: BiomeId) {
  return biomeDefinitions[id];
}
