import type { Facing, KnockbackMotion } from '../state';
import type { LootTable } from '../loot';
import type { StatusEffectInstance } from '../status-effects/types';
import type { ProjectileDefinition } from '../../../shared/content';

export type AdventureClanId = 'player' | 'neutral' | `camp-${string}`;

export type AdventureEnemyDefinition = {
  id: string;
  name: string;
  body: string;
  leftHand?: string;
  rightHand?: string;
  deathBody: string;
  deathLeftHand?: string;
  deathRightHand?: string;
  color: string;
  pillWidth: number;
  maxHp: number;
  attack: number;
  knockback: number;
  speed: number;
  attackSpeed: number;
  attackRange: number;
  attackKind: 'melee' | 'ranged';
  projectile?: ProjectileDefinition;
  projectileSpeed: number;
  projectileRadius: number;
  alertRadius: number;
  chaseRadius: number;
  aggroRadius: number;
  loot?: LootTable;
};

export type AdventureEnemy = {
  id: string;
  chunkKey?: string;
  defId: string;
  name: string;
  x: number;
  y: number;
  spawnX: number;
  spawnY: number;
  hp: number;
  maxHp: number;
  facing: Facing;
  radius: number;
  body: string;
  leftHand?: string;
  rightHand?: string;
  deathBody: string;
  deathLeftHand?: string;
  deathRightHand?: string;
  color: string;
  pillWidth: number;
  attack: number;
  knockback: number;
  speed: number;
  attackSpeed: number;
  attackRange: number;
  attackKind: 'melee' | 'ranged';
  projectile?: ProjectileDefinition;
  projectileSpeed: number;
  projectileRadius: number;
  alertRadius: number;
  chaseRadius: number;
  aggroRadius: number;
  attackReadyAt: number;
  clanId: AdventureClanId;
  knockbackMotion?: KnockbackMotion;
  alerted: boolean;
  alertedAt?: number;
  statusEffects: StatusEffectInstance[];
  invulnerable?: boolean;
  loot?: LootTable;
};
